### ISSUE TITLE
Facebook Birthday Calendar events not seen as fullDayEvent

### ISSUE THREAD

**Issue by Modderhut** [eouia/MMM-CalendarExt#24]
Let me start with saying I'm very impressed with this nice module! furthermore I'm not a coder!

When I import Facebook birthdays webcal://www.facebook.com/ical/b.php?uid=********&key=*******    some odd things happen.  They are displayed over two days and the event time is displayed in  endDateTime - beginDateTime  (jan 2nd 23:59 - jan 1st 00:00 ).

Is I initially thought this was me making a config mistake I opened a  forum topic about this too;
 [link](https://forum.magicmirror.builders/topic/6563/mmm-calendarext-facebook-birtday-events-shown-on-two-days) 

I believe the calendar event is not recognized as fullDayEvent as the CSS formatting for that is not applied. I think the code is exspecting  "duration" not to be filled.
example facebook ical;

BEGIN:VCALENDAR
--
PRODID:-//Facebook//NONSGML   Facebook Events V1.0//EN
X-WR-CALNAME:Friends' Birthdays
X-PUBLISHED-TTL:PT12H
X-ORIGINAL-URL:/events/birthdays/
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
DTSTART:20180219
SUMMARY:Martin van Drunen's birthday
RRULE:FREQ=YEARLY
**DURATION:P1D**
UID:*****@facebook.com
END:VEVENT

thanks!

**Comment by eouia** [comment]
I fixed this issue (I'm thinking so). Try new commit.

**Comment by Modderhut** [comment]
thanks for your quick follow up! The event is now formatted as full day event

**Comment by Modderhut** [comment]
closed it to quickly, the event is still shown over two days, I'll post a screen in the forum

**Comment by eouia** [comment]
I got it. I found it also. sorry for my too early fix. I'll check more deeply.

**Comment by eouia** [comment]
I did. try again.

**Comment by Modderhut** [comment]
perfect! solved. Thanks again for the quick help.
